title = "The DIY-student"
baseURL = "https://www.nielsburghoorn.com"
theme = "hugo-theme-stack"
googleAnalytics = "UA-194957504-1"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_020

  [params.dateFormat] #numbers are non-meaningful only for formatting
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = ""
  subtitle = "Welcome to the blog and portfolio of Niels Burghoorn"

    [params.sidebar.avatar]
    local = true
    src = "img/diy-niels (2).jpeg"

  [params.article]
  math = false

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "disqus"

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

  [params.widgets]
  enabled = [ "search", "archives", "tag-cloud" ]

    [params.widgets.archives]
    limit = 5

    [params.widgets.tagCloud]
    limit = 10

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"

# [related]
# includeNewer = true
# threshold = 60
# toLower = false

#   [[related.indices]]
#   name = "tags"
#   weight = 100

#   [[related.indices]]
#   name = "categories"
#   weight = 200

[markup.highlight]
noClasses = false
